const fs = require('fs');

// Create a simple PNG favicon using base64 data
// This is a 32x32 orange square with white "E" letter
const faviconBase64 = `iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE4SURBVFhHxZc9SwNBEIafxsLGwsJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCwcJCQUFBQ==`;

try {
  // Convert base64 to buffer and write to file
  const buffer = Buffer.from(faviconBase64, 'base64');
  fs.writeFileSync('./assets/favicon.png', buffer);
  console.log('Favicon created successfully');
} catch (error) {
  console.error('Error creating favicon:', error);
  
  // Fallback: just copy from existing file
  try {
    const truckIcon = fs.readFileSync('./assets/truck-icon.png');
    fs.writeFileSync('./assets/favicon.png', truckIcon);
    console.log('Favicon copied from truck-icon.png');
  } catch (copyError) {
    console.error('Error copying favicon:', copyError);
  }
}
